name: npm Publish

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn type-check
            - run: yarn test
            - run: yarn build
            - uses: actions/upload-artifact@v2
              with:
                  name: build-output
                  path: dist
                  if-no-files-found: error
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
